name: MultiCalculator
options:
  developmentLanguage: ja
  xcodeVersion: 11.5
config:
  Debug: debug
  Release: release
targets:
  MultiCalculator:
    type: application
    platform: iOS
    developmentTarget: 13.0
    sources:
      - path: MultiCalculator
    scheme: {}
    dependencies:
      - target: Shared
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: true
        DEVELOPMENT_TEAM: AV9FQ3YF56
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.tomoki-sun.app.ios.multi-calculator
          PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Debug.plist
          CODE_SIGN_ENTITLEMENTS: MultiCalculator/Resources/Entitlements/Debug.entitlements
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.tomoki-sun.app.ios.multi-calculator
          PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Release.plist
          CODE_SIGN_ENTITLEMENTS: MultiCalculator/Resources/Entitlements/Release.entitlements
  MultiCalculatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MultiCalculatorTests
    dependencies:
      - target: MultiCalculator
    scheme:
      gatherCoverageData: true
      testTargets:
        - MultiCalculatorTests

  Shared:
    type: framework
    platform: iOS
    developmentTarget: 13.1.3
    sources: Shared
    scheme:
      gatherCoverageData: true
      testTargets: 
        - SharedTests
    settings:
      base:        
        PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator.shared
  
  SharedTests:
    type: bundle.unit-test
    platform: iOS
    sources: SharedTests