name: MultiCalculator
fileGroups:
  - README.md
options:
  developmentLanguage: ja
  xcodeVersion: 11.5
config:
  Debug: debug
  Release: release
targets:
  MultiCalculator:
    type: application
    platform: iOS
    developmentTarget: 13.0
    sources:
      - path: MultiCalculator
    scheme: {}
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: AV9FQ3YF56
        PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Debug.plist
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Release.plist
  MultiCalculatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MultiCalculatorTests
    dependencies:
      - target: MultiCalculator
    scheme:
      testTargets:
        - MultiCalculatorTests
