name: MultiCalculator
options:
  developmentLanguage: ja
  xcodeVersion: 11.5
config:
  Debug: debug
  Release: release
targets:
  MultiCalculator:
    type: application
    platform: iOS
    developmentTarget: 13.0
    sources:
      - path: MultiCalculator
    scheme: {}
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: true
        DEVELOPMENT_TEAM: AV9FQ3YF56
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Debug.plist
          CODE_SIGN_ENTITLEMENTS: MultiCalculator/Resources/Entitlements/Debug.entitlements
          PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          INFOPLIST_FILE: MultiCalculator/Resources/Info/Release.plist
          CODE_SIGN_ENTITLEMENTS: MultiCalculator/Resources/Entitlements/Release.entitlements
          PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.multi-calculator
  MultiCalculatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MultiCalculatorTests
    dependencies:
      - target: MultiCalculator
    scheme:
      gatherCoverageData: true
      testTargets:
        - MultiCalculatorTests
