name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  xcode:
    runs-on: macos-latest
    name: Xcode 11.5
    env:
      DEVELOPER_DIR: "/Applications/Xcode_11.5.app"
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: make install
      - name: iOS test
        run: xcodebuild build-for-testing -project MultiCalculator.xcodeproj -scheme MultiCalculatorTests -destination 'generic/platform=iOS Simulator' ENABLE_TESTABILITY=YES
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
        if: success()